### PR TITLE
add vast tag

### PR DESCRIPTION
**Pull request by darshanbib**
@till LMK what you think.. seems to work when I do `http://easybib.bib/vmntribes-vast-tag/`

screen shot 2015-04-21 at 6 35 50 pm

Re: https://github.com/easybib/issues/issues/3931#issuecomment-94958679

### CODE REVIEW

**Comment by till** [comment]
@darshanbib @fh I think we should set aggressive `proxy_read_timeout` and `proxy_send_timeout` so we don't go down when something in between us and burstnet has issues.

**Comment by fh** [comment]
@till Yes! If this causes issues and we need longer timeouts, we could also reroute this on some specific instance in LB based on an ACL, so not everything blows up. Also, lets include this in some sort of conditional, easybib.com.conf.erb is being used for at least autocite and rr as well.

**Comment by till** [comment]
@darshanbib See comments, let me know if you need help!

**Comment by darshanbib** [comment]
@till @fh I added the timeout flags. Is `3s` ok? 

Re: the conditional and LB ACL routing, do you guys have an example I can look at? I put this code in the same section where we have our other [ad code + blocking script sections](https://github.com/till/easybib-cookbooks/blob/t/3931_vast/nginx-app/templates/default/easybib.com.conf.erb#L16-L25).

**Comment by till** [comment]
@darshanbib This is never gonna work. Statements terminate with `;`. Please try this out.

**Comment by darshanbib** [comment]
@till I did, but I didn't reprovision so that's why it kept working.. trying this out now.

**Comment by darshanbib** [comment]
Seems to work. 

Btw, is there a linter I can run for this sort of stuff?

**Comment by till** [comment]
@darshanbib I think in vagrant: `/etc/init.d/nginx configtest`

**Comment by till** [comment]
@darshanbib http://nginx.org/en/docs/http/ngx_http_proxy_module.html < search for timeout. Sorry, I forgot `proxy_connect_timeout`. Looks good otherwise!

**Comment by darshanbib** [comment]
@till I added the new flag and ran `/etc/init.d/nginx configtest`. Initially it was failing, but I had to add double quotes to the `proxy_set_header` line to make it pass.

New config is in:
screen shot 2015-04-22 at 10 31 23 am

configtest:
screen shot 2015-04-22 at 10 31 47 am

(FYI it passes as sudo but not without sudo; although this is the same with the old config file as well).

**Pull request merged**
