### PR TITLE
Fixes for research ready vagrant not building against migrated chef recipes

### PR DESCRIPTION
**Pull request by gilleyj**
in nginx-app/recipes/role-vagrant.rb
    nginx-app:vagrant to nginx-app:vagrant-silex

in nginx-app/recipes/vagrant-silex.rb
    include recipe supervisor

### CODE REVIEW

**Comment by sodoku** [comment]
@gilleyj files at `/static` are not found (404). e.g. `http://app.dev.ieacademy.com/static/analytics/css/app.css`

All built files end up in
`app/modules/infolit/www-src/static/analytics/`
as mentioned here https://github.com/easybib/researchready/blob/master/docs/frontend.md#tasks

As mentioned here https://github.com/easybib/researchready/pull/5158#issuecomment-218418386 the node-gyp errors can be ignored.

**Comment by sodoku** [comment]
@gilleyj this might help https://github.com/till/easybib-cookbooks/blob/0bb2c2d710209ce09adddcaedd4a64f5c3dfeaa3/nginx-app/templates/default/infolit.conf.erb#L66

**Comment by till** [comment]
@gilleyj so, this should use `infolit.conf.erb`. And then it works. The other might use the generic silex configuration.

**Comment by dazz** [comment]
@till @gilleyj could this part live in the academy `nginx.conf` ?

https://github.com/easybib/researchready/blob/master/deploy/nginx.conf

**Comment by till** [comment]
@dazz there is a lot of customisation in the template for the old app. Would like to not start that right now. ;) Let's just get the `infolit.conf.erb` used.

**Comment by till** [comment]
@gilleyj I think we should restart this PR. Academy must run with `infolit.conf.erb`

**Comment by till** [comment]
Fixing this in #1017

**Pull request closed without merging**
