### PR TITLE
add nginx-trust-cert

### PR DESCRIPTION
**Pull request by appmode**
This should fix https://github.com/easybib/issues/issues/3953

I haven't tested this yet (because I'm not sure how) and it's my first cookbook so I'm really just guessing at how it's all supposed to work.

### CODE REVIEW

**Comment by till** [comment]
@appmode As discussed on Flowdock, let me know if you still need help (manually) testing this.

Also, for feedback, I would like to reconsider editing that file because of the comment inside the file:

```
# This file lists certificates that you wish to use or to ignore to be
# installed in /etc/ssl/certs.
# update-ca-certificates(8) will update /etc/ssl/certs by reading this file.
#
# This is autogenerated by dpkg-reconfigure ca-certificates.
# Certificates should be installed under /usr/share/ca-certificates
# and files with extension '.crt' is recognized as available certs.
#
# line begins with # is comment.
# line begins with ! is certificate filename to be deselected.
#
```

Seems like updates to it would override what you did. So maybe there is a better way to invoke `dpkg-reconfigure`?

**Comment by appmode** [comment]
I'll test out `dpkg-reconfigure ca-certificates` and see how it works

**Comment by appmode** [comment]
@till dpkg-reconfigure reads the /etc/ca-certificates.conf file and checks the contents of /usr/share/ca-certificates/ before regenerating the file, so our changes to the file do not get overwritten.

**Comment by till** [comment]
@appmode OK, so then, let me know if this fixes the issue and we can merge this.

**Comment by fh** [comment]
Maybe call this from [`easybib-deploy::ssl-vagrant`](https://github.com/till/easybib-cookbooks/blob/master/easybib-deploy/recipes/ssl-vagrant.rb) or even add this there to make sure it is executed every time.
You could also use the mechanism [used to generate `cert.pem`](https://github.com/till/easybib-cookbooks/blob/master/easybib-deploy/recipes/ssl-vagrant.rb#L18-L27) to generate `/usr/share/ca-certificates/nginx.crt`. This way, this cookbook wont break when someone decides to rename/change the nginx certificate setup in vagrant.

**Comment by appmode** [comment]
I agree that it makes sense to move the functionality into easybib-deploy::ssl-vagrant so I have done so.

I don't think it would make sense to generate `/usr/share/ca-certificates/nginx.crt` because it needs to match the certificate used by nginx, so we would also need to copy the certificate to the nginx folder, and if the nginx certificate setup did get changed somewhere else then this cookbook would not fail but the functionality it provides would be broken.

**Comment by appmode** [comment]
@till I've manually tested this and confirmed that it does what it's supposed to, so it's ready to be merged if you're happy with it.

**Comment by till** [comment]
@appmode :clap: nice work

**Pull request merged**
