### PR TITLE
stack-scholar::role-vagrant replace rabbitMQ recipe with with fakesqs

### PR DESCRIPTION
**Pull request by gilleyj**
Related to [DEVOPS-156](https://imagineeasy.atlassian.net/browse/DEVOPS-156) DEVOPS-156

Depends on https://github.com/till/easybib-cookbooks/pull/1025

Dependency of https://github.com/easybib/scholar-vagrant/pull/163

### CODE REVIEW

**Comment by gilleyj** [comment]
Fails because of dependency on https://github.com/till/easybib-cookbooks/pull/1025

**Comment by till** [comment]
@gilleyj feel free to re-base!

**Comment by gilleyj** [comment]
@till rebased and fixed

**Comment by till** [comment]
@gilleyj thanks, I think we'll wait for Monday to circle back with the team if we do this.

**Comment by gilleyj** [comment]
Sounds good to me!

**Pull request closed without merging**
